module.exports = {  
  config: {  
    name: "command_name",                // 🔹 Command Name  
    version: "1.0",                      // 🔸 Version  
    author: "xnil6x",                    // 👨‍💻 Developer  
    role: 4,                             // 🔐 Required Access Level  
    usePrefix: true,                     // ⛓️ Prefix Requirement  
    description: "Command Description",   // 📝 Functionality  
    guide: "Usage Guide",                // 📘 Command Syntax  
    category: "Utility",                 // 🧰 Function Category  
    cooldowns: 3                         // ⏳ Execution Delay (seconds)  
  }  
};
